# Generated by Django 4.0.1 on 2022-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
