# Generated by Django 4.0.1 on 2022-01-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_staff'),
        ('orders', '0003_alter_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=250)),
                ('staff_called', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='service.staff')),
            ],
        ),
    ]
