# Generated by Django 4.0.1 on 2022-01-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_callitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callitem',
            name='staff_called',
        ),
        migrations.AddField(
            model_name='callitem',
            name='order',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order'),
        ),
    ]
