# Generated by Django 4.0.1 on 2022-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_item_available_alter_item_category_alter_item_image'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='item',
            index_together={('slug', 'id')},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
