# Generated by Django 4.0.1 on 2022-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_item_index_together_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
