# Generated by Django 4.0.1 on 2022-01-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_item_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='items/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
