# Generated by Django 4.0.1 on 2022-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(db_index=True, default='shishamaster', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(db_index=True, default='Andrei', max_length=200),
        ),
    ]
